addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.10.4")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.5.11")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.5.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "2.0.6")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"        % "0.4.4")
