addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"   % "0.11.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release" % "1.6.1")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"   % "0.5.2")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"  % "2.0.10")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.7")
